[theme]
primaryColor = "#2563EB"         # buttons/accents (Tailwind blue-600)
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F6F8FB"  # cards/sidebars
textColor = "#0F172A"            # slate-900
font = "Inter"                   # or "Sans Serif"
